---
title: "Practical_2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)
```

Creating a decomposition matrix from raw data

Step 1
```{r}
dmx <- tibble(i=rep(1:3,each=4), j=rep(1:4,times=3), Yij=c(37, 80, 64, 51, 33, 47, 55, 41, 59, 23, 50, 60))
```

Step 2
```{r}
dmx2 <- dmx %>% mutate(mu = mean(Yij))
```

Step 3
```{r}
dmx3 <- dmx2 %>% group_by(i) %>% mutate(Ai= mean(Yij) - mu) %>% ungroup()
```

Step 4
```{r}
dmx4 <- dmx3 %>% mutate(err=Yij-(mu+Ai))
```

Step 5 
```{r}
dmx4 <- dmx4 %>% mutate(Yij2=Yij^2, 
                        mu2=mu^2, 
                        Ai2=Ai^2, 
                        err2=err^2) 

sstbl <- dmx4 %>% summarise(ss_Y = sum(Yij2), 
                            ss_mu = sum(mu2), 
                            ss_Ai = sum(Ai2), 
                            ss_err = sum(err2))
```

Step 6
```{r}
# df between groups (df_effect): number of groups - 1
df_num = 3 - 1  # 2

# df within group (df_error): total number of participants - number of groups
df_denom = 12 - 3  # 9
```

```{r}
MSA <- 416/df_num  # 416 = SS_Ai (found in sstbl)

MSSA <- 2164/df_denom  # 2164 = SS_err (found in sstbl)
```

```{r}
F <- MSA/MSSA
```


Step 7
```{r}
p = pf(F, df_num, df_denom, lower.tail = FALSE)

p
```


# The Easy Way: ezANOVA FUNCTION
```{r}
# install.packages('ez')
library(ez)
```

```{r}
dmx <- dmx %>% mutate(ID=1:12,i=as.factor(i)) 
```

```{r}
ezANOVA(dmx,
        wid = ID,
        dv = Yij,
        between = i,
        detailed = TRUE)
```




